w0 = pi/3;
r = 0.6;
[b,a]=notch_with_3(w0,r);
n = 0:50;
X1 = sin(w0*n)+sin(2*w0*n);
%X2 = sin(2*w0*n);
y1 = filter(b,a,X1);
%y2 = filter(a,b,X2);
subplot(221);
plot(n,X1);
title("Original signal");
subplot(222);
plot(n,y1);
title("Filtered signal");
subplot(223);
plot(n,abs(fft(X1)));
title("Frequency response for original signal");
subplot(224);
plot(n,abs(fft(y1)));
title("Frequency response for filtered signal");